//
// Created by ubuntu on 2023/8/22.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include "uart_io_api.h"
#include "serial_datagram.h"
/* Header for class com_huaqin_serialport_SerialPort */

#ifndef _Included_com_huaqin_serialport_SerialPort
#define _Included_com_huaqin_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huaqin_serialport_SerialPort
 * Method:    initUart
 * Signature: ()Z
 */

JNIEXPORT jboolean JNICALL Java_com_huaqin_serialport_SerialPort_initUart
        (JNIEnv *, jobject){
    bool ret;
    printf("zhangwencai initUart");
    ret = init_uart_io_api();
    printf("zhangwencai %d for init_uart_io_api\n", ret);
    return ret;
}

/*
 * Class:     com_huaqin_serialport_SerialPort
 * Method:    serialDatagramSend
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_com_huaqin_serialport_SerialPort_serialDatagramSend
        (JNIEnv *, jclass){
    serial_datagram_send(123, 0x08, NULL, 0);
}

/*
 * Class:     com_huaqin_serialport_SerialPort
 * Method:    serialDatagramReceiveLoop
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_com_huaqin_serialport_SerialPort_serialDatagramReceiveLoop
        (JNIEnv *, jobject){
    serial_datagram_receive_loop(0);
}

#ifdef __cplusplus
}
#endif
#endif
