// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.protobufdemo;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface nfc_dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nfc_data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string OPEN = 2;</code>
     * @return The oPEN.
     */
    java.lang.String getOPEN();
    /**
     * <code>string OPEN = 2;</code>
     * @return The bytes for oPEN.
     */
    com.google.protobuf.ByteString
        getOPENBytes();

    /**
     * <code>string rand = 3;</code>
     * @return The rand.
     */
    java.lang.String getRand();
    /**
     * <code>string rand = 3;</code>
     * @return The bytes for rand.
     */
    com.google.protobuf.ByteString
        getRandBytes();

    /**
     * <code>string colse = 4;</code>
     * @return The colse.
     */
    java.lang.String getColse();
    /**
     * <code>string colse = 4;</code>
     * @return The bytes for colse.
     */
    com.google.protobuf.ByteString
        getColseBytes();
  }
  /**
   * Protobuf type {@code nfc_data}
   */
  public static final class nfc_data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nfc_data)
      nfc_dataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use nfc_data.newBuilder() to construct.
    private nfc_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private nfc_data() {
      oPEN_ = "";
      rand_ = "";
      colse_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new nfc_data();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobufdemo.Test.internal_static_nfc_data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobufdemo.Test.internal_static_nfc_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobufdemo.Test.nfc_data.class, com.example.protobufdemo.Test.nfc_data.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int OPEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object oPEN_;
    /**
     * <code>string OPEN = 2;</code>
     * @return The oPEN.
     */
    @java.lang.Override
    public java.lang.String getOPEN() {
      java.lang.Object ref = oPEN_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oPEN_ = s;
        return s;
      }
    }
    /**
     * <code>string OPEN = 2;</code>
     * @return The bytes for oPEN.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOPENBytes() {
      java.lang.Object ref = oPEN_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oPEN_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RAND_FIELD_NUMBER = 3;
    private volatile java.lang.Object rand_;
    /**
     * <code>string rand = 3;</code>
     * @return The rand.
     */
    @java.lang.Override
    public java.lang.String getRand() {
      java.lang.Object ref = rand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rand_ = s;
        return s;
      }
    }
    /**
     * <code>string rand = 3;</code>
     * @return The bytes for rand.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRandBytes() {
      java.lang.Object ref = rand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLSE_FIELD_NUMBER = 4;
    private volatile java.lang.Object colse_;
    /**
     * <code>string colse = 4;</code>
     * @return The colse.
     */
    @java.lang.Override
    public java.lang.String getColse() {
      java.lang.Object ref = colse_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        colse_ = s;
        return s;
      }
    }
    /**
     * <code>string colse = 4;</code>
     * @return The bytes for colse.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getColseBytes() {
      java.lang.Object ref = colse_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oPEN_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, oPEN_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rand_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rand_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colse_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, colse_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oPEN_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, oPEN_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rand_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, rand_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colse_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, colse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobufdemo.Test.nfc_data)) {
        return super.equals(obj);
      }
      com.example.protobufdemo.Test.nfc_data other = (com.example.protobufdemo.Test.nfc_data) obj;

      if (getId()
          != other.getId()) return false;
      if (!getOPEN()
          .equals(other.getOPEN())) return false;
      if (!getRand()
          .equals(other.getRand())) return false;
      if (!getColse()
          .equals(other.getColse())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + getOPEN().hashCode();
      hash = (37 * hash) + RAND_FIELD_NUMBER;
      hash = (53 * hash) + getRand().hashCode();
      hash = (37 * hash) + COLSE_FIELD_NUMBER;
      hash = (53 * hash) + getColse().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobufdemo.Test.nfc_data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobufdemo.Test.nfc_data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.protobufdemo.Test.nfc_data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobufdemo.Test.nfc_data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobufdemo.Test.nfc_data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nfc_data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nfc_data)
        com.example.protobufdemo.Test.nfc_dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobufdemo.Test.internal_static_nfc_data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobufdemo.Test.internal_static_nfc_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobufdemo.Test.nfc_data.class, com.example.protobufdemo.Test.nfc_data.Builder.class);
      }

      // Construct using com.example.protobufdemo.Test.nfc_data.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        oPEN_ = "";

        rand_ = "";

        colse_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobufdemo.Test.internal_static_nfc_data_descriptor;
      }

      @java.lang.Override
      public com.example.protobufdemo.Test.nfc_data getDefaultInstanceForType() {
        return com.example.protobufdemo.Test.nfc_data.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobufdemo.Test.nfc_data build() {
        com.example.protobufdemo.Test.nfc_data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobufdemo.Test.nfc_data buildPartial() {
        com.example.protobufdemo.Test.nfc_data result = new com.example.protobufdemo.Test.nfc_data(this);
        result.id_ = id_;
        result.oPEN_ = oPEN_;
        result.rand_ = rand_;
        result.colse_ = colse_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobufdemo.Test.nfc_data) {
          return mergeFrom((com.example.protobufdemo.Test.nfc_data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobufdemo.Test.nfc_data other) {
        if (other == com.example.protobufdemo.Test.nfc_data.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getOPEN().isEmpty()) {
          oPEN_ = other.oPEN_;
          onChanged();
        }
        if (!other.getRand().isEmpty()) {
          rand_ = other.rand_;
          onChanged();
        }
        if (!other.getColse().isEmpty()) {
          colse_ = other.colse_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();

                break;
              } // case 8
              case 18: {
                oPEN_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                rand_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                colse_ = input.readStringRequireUtf8();

                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object oPEN_ = "";
      /**
       * <code>string OPEN = 2;</code>
       * @return The oPEN.
       */
      public java.lang.String getOPEN() {
        java.lang.Object ref = oPEN_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oPEN_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string OPEN = 2;</code>
       * @return The bytes for oPEN.
       */
      public com.google.protobuf.ByteString
          getOPENBytes() {
        java.lang.Object ref = oPEN_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oPEN_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string OPEN = 2;</code>
       * @param value The oPEN to set.
       * @return This builder for chaining.
       */
      public Builder setOPEN(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oPEN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string OPEN = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOPEN() {
        
        oPEN_ = getDefaultInstance().getOPEN();
        onChanged();
        return this;
      }
      /**
       * <code>string OPEN = 2;</code>
       * @param value The bytes for oPEN to set.
       * @return This builder for chaining.
       */
      public Builder setOPENBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oPEN_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rand_ = "";
      /**
       * <code>string rand = 3;</code>
       * @return The rand.
       */
      public java.lang.String getRand() {
        java.lang.Object ref = rand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rand = 3;</code>
       * @return The bytes for rand.
       */
      public com.google.protobuf.ByteString
          getRandBytes() {
        java.lang.Object ref = rand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rand = 3;</code>
       * @param value The rand to set.
       * @return This builder for chaining.
       */
      public Builder setRand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rand = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRand() {
        
        rand_ = getDefaultInstance().getRand();
        onChanged();
        return this;
      }
      /**
       * <code>string rand = 3;</code>
       * @param value The bytes for rand to set.
       * @return This builder for chaining.
       */
      public Builder setRandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object colse_ = "";
      /**
       * <code>string colse = 4;</code>
       * @return The colse.
       */
      public java.lang.String getColse() {
        java.lang.Object ref = colse_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          colse_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string colse = 4;</code>
       * @return The bytes for colse.
       */
      public com.google.protobuf.ByteString
          getColseBytes() {
        java.lang.Object ref = colse_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          colse_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string colse = 4;</code>
       * @param value The colse to set.
       * @return This builder for chaining.
       */
      public Builder setColse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        colse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string colse = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearColse() {
        
        colse_ = getDefaultInstance().getColse();
        onChanged();
        return this;
      }
      /**
       * <code>string colse = 4;</code>
       * @param value The bytes for colse to set.
       * @return This builder for chaining.
       */
      public Builder setColseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        colse_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nfc_data)
    }

    // @@protoc_insertion_point(class_scope:nfc_data)
    private static final com.example.protobufdemo.Test.nfc_data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobufdemo.Test.nfc_data();
    }

    public static com.example.protobufdemo.Test.nfc_data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<nfc_data>
        PARSER = new com.google.protobuf.AbstractParser<nfc_data>() {
      @java.lang.Override
      public nfc_data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<nfc_data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<nfc_data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobufdemo.Test.nfc_data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nfc_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nfc_data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"A\n\010nfc_data\022\n\n\002id\030\001 \001(\003\022\014\n\004" +
      "OPEN\030\002 \001(\t\022\014\n\004rand\030\003 \001(\t\022\r\n\005colse\030\004 \001(\tB" +
      "\032\n\030com.example.protobufdemob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nfc_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nfc_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nfc_data_descriptor,
        new java.lang.String[] { "Id", "OPEN", "Rand", "Colse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
