:: Windows batch program that generates nanopb message.c/.h files during Keil's build process

:: Get the current directory of this bat file
setLocal enableDelayedExpansion
set mcu_root_dir=%~dp0

:: nanopb needs to be cloned in advance, and the directory is at the same level as our git repo. So it can be found like this
set nanopb_repo_root=%mcu_root_dir%..\..\nanopb

:: The directory where remote_message.proto and .options are located
set src_dir=%mcu_root_dir%..\src

:: The directory of the pb file generated by nanopb tool, which has remote_message.pb.c .h
set nanopb_intermediate_dir=%mcu_root_dir%\..\nanopb_intermediate

:: clean the target files
del %nanopb_intermediate_dir%\*.c
del %nanopb_intermediate_dir%\*.h

:: Switch to the directory where remote_message.proto is located
:: calls the python command to generate the files
cd %src_dir%
python.exe "%nanopb_repo_root%\generator\protoc" --nanopb_out=%nanopb_intermediate_dir% remote_message.proto
:: then exit with the python's error code. hope it's 0
exit /b %ERRORLEVEL%