#ifndef _RIL_COMMAND_H
#define _RIL_COMMAND_H

//solicited message
#define RIL_REQUEST_GET_SIM_STATUS 1
#define RIL_REQUEST_SETUP_DATA_CALL 27
#define RIL_REQUEST_DEACTIVATE_DATA_CALL 41
#define RIL_REQUEST_RADIO_POWER 23
#define RIL_REQUEST_VOICE_REGISTRATION_STATE 20
#define RIL_REQUEST_DATA_REGISTRATION_STATE 21
#define RIL_REQUEST_OPERATOR 22
//Add by wangcong for ICCID
#define RIL_REQUEST_SIM_IO 28
#define RIL_REQUEST_SIGNAL_STRENGTH 19
//Add by wangcong for IMSI
#define RIL_REQUEST_GET_IMSI 11
//Add by wangcong for PDP
#define RIL_REQUEST_DATA_CALL_LIST 57
//Add by wangcong for Gprs
#define RIL_REQUEST_GET_CELL_INFO_LIST 109
#define RIL_REQUEST_SET_INITIAL_ATTACH_APN 111
//Add by wangcong for Gprs
#define RIL_REQUEST_SEND_AT 5050
#define RIL_REQUEST_GET_GPRS_ATTACH_STATE 5083
//Add by wangcong for IMEI
#define RIL_REQUEST_GET_IMEI 38
//unsolicited message
#define RIL_UNSOL_RIL_CONNECTED 1034
#define RIL_UNSOL_RESPONSE_RADIO_STATE_CHANGED 1000
#define RIL_UNSOL_RESPONSE_VOICE_NETWORK_STATE_CHANGED 1002
#define RIL_UNSOL_RESPONSE_SIM_STATUS_CHANGED 1019
#define RIL_UNSOL_DATA_CALL_LIST_CHANGED 1010

#endif