# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14remote_message.proto\"/\n\tlogin_req\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\tlogin_res\x12\x1a\n\x06status\x18\x01 \x01(\x0e\x32\n.boolean_t\"\x1b\n\nlogout_req\x12\r\n\x05\x64ummy\x18\x01 \x01(\x05\"(\n\nlogout_res\x12\x1a\n\x06status\x18\x01 \x01(\x0e\x32\n.boolean_t\"/\n\x07key_evt\x12\x10\n\x08key_code\x18\x01 \x01(\x05\x12\x12\n\nkey_action\x18\x02 \x01(\x08\"%\n\x07log_evt\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"X\n\x06to_mcu\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\x1b\n\x05login\x18\x03 \x01(\x0b\x32\n.login_reqH\x00\x12\x1d\n\x06logout\x18\x04 \x01(\x0b\x32\x0b.logout_reqH\x00\x42\x05\n\x03req\"\xb7\x01\n\x08\x66rom_mcu\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\'\n\x08\x65rr_code\x18\x02 \x01(\x0e\x32\x15.remote_call_err_code\x12\x1b\n\x05login\x18\x03 \x01(\x0b\x32\n.login_resH\x00\x12\x1d\n\x06logout\x18\x04 \x01(\x0b\x32\x0b.logout_resH\x00\x12\x18\n\x03key\x18\xc9\x01 \x01(\x0b\x32\x08.key_evtH\x00\x12\x18\n\x03log\x18\xca\x01 \x01(\x0b\x32\x08.log_evtH\x00\x42\x05\n\x03res*\x93\x01\n\x14remote_call_err_code\x12\x06\n\x02ok\x10\x00\x12\x0b\n\x07\x63rc_err\x10\x01\x12\x10\n\x0creq_type_err\x10\x02\x12\x0b\n\x07\x66mt_err\x10\x03\x12\x0b\n\x07no_impl\x10\x04\x12\x11\n\rsrv_not_ready\x10\x05\x12\x0c\n\x08parm_err\x10\x06\x12\x0b\n\x07timeout\x10\x07\x12\x0c\n\x08\x63omm_err\x10\x08*3\n\tboolean_t\x12\n\n\x06\x66\x61iled\x10\x00\x12\r\n\tsucceeded\x10\x01\x12\x0b\n\x07unknown\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REMOTE_CALL_ERR_CODE']._serialized_start=550
  _globals['_REMOTE_CALL_ERR_CODE']._serialized_end=697
  _globals['_BOOLEAN_T']._serialized_start=699
  _globals['_BOOLEAN_T']._serialized_end=750
  _globals['_LOGIN_REQ']._serialized_start=24
  _globals['_LOGIN_REQ']._serialized_end=71
  _globals['_LOGIN_RES']._serialized_start=73
  _globals['_LOGIN_RES']._serialized_end=112
  _globals['_LOGOUT_REQ']._serialized_start=114
  _globals['_LOGOUT_REQ']._serialized_end=141
  _globals['_LOGOUT_RES']._serialized_start=143
  _globals['_LOGOUT_RES']._serialized_end=183
  _globals['_KEY_EVT']._serialized_start=185
  _globals['_KEY_EVT']._serialized_end=232
  _globals['_LOG_EVT']._serialized_start=234
  _globals['_LOG_EVT']._serialized_end=271
  _globals['_TO_MCU']._serialized_start=273
  _globals['_TO_MCU']._serialized_end=361
  _globals['_FROM_MCU']._serialized_start=364
  _globals['_FROM_MCU']._serialized_end=547
# @@protoc_insertion_point(module_scope)
