# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14remote_message.proto\"/\n\tlogin_req\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\tlogin_res\x12\x1a\n\x06status\x18\x01 \x01(\x0e\x32\n.boolean_t*3\n\tboolean_t\x12\n\n\x06\x66\x61iled\x10\x00\x12\r\n\tsucceeded\x10\x01\x12\x0b\n\x07unknown\x10\x02\x62\x06proto3')
)

_BOOLEAN_T = _descriptor.EnumDescriptor(
  name='boolean_t',
  full_name='boolean_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='failed', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='succeeded', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='unknown', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=114,
  serialized_end=165,
)
_sym_db.RegisterEnumDescriptor(_BOOLEAN_T)

boolean_t = enum_type_wrapper.EnumTypeWrapper(_BOOLEAN_T)
failed = 0
succeeded = 1
unknown = 2



_LOGIN_REQ = _descriptor.Descriptor(
  name='login_req',
  full_name='login_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='login_req.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='login_req.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=71,
)


_LOGIN_RES = _descriptor.Descriptor(
  name='login_res',
  full_name='login_res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='login_res.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=112,
)

_LOGIN_RES.fields_by_name['status'].enum_type = _BOOLEAN_T
DESCRIPTOR.message_types_by_name['login_req'] = _LOGIN_REQ
DESCRIPTOR.message_types_by_name['login_res'] = _LOGIN_RES
DESCRIPTOR.enum_types_by_name['boolean_t'] = _BOOLEAN_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

login_req = _reflection.GeneratedProtocolMessageType('login_req', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_REQ,
  __module__ = 'remote_message_pb2'
  # @@protoc_insertion_point(class_scope:login_req)
  ))
_sym_db.RegisterMessage(login_req)

login_res = _reflection.GeneratedProtocolMessageType('login_res', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_RES,
  __module__ = 'remote_message_pb2'
  # @@protoc_insertion_point(class_scope:login_res)
  ))
_sym_db.RegisterMessage(login_res)


# @@protoc_insertion_point(module_scope)
